const state={conferences:[],area:"All",ccf:"all",query:"",timezone:"local"};
const areaLabels={All:"全部",Robotics:"机器人",AI:"人工智能",ML:"机器学习",Vision:"计算机视觉"};
const elements={list:document.querySelector("#conference-list"),template:document.querySelector("#conference-card-template"),empty:document.querySelector("#empty-state"),search:document.querySelector("#search"),ccfFilter:document.querySelector("#ccf-filter"),areaFilters:document.querySelector("#area-filters"),timezoneToggle:document.querySelector("#timezone-toggle"),upcomingCount:document.querySelector("#upcoming-count"),tbaCount:document.querySelector("#tba-count"),conferenceCount:document.querySelector("#conference-count"),lastUpdated:document.querySelector("#last-updated")};
function deadlineDate(c){return c.deadline?new Date(c.deadline):null}
function formatDeadline(c){const d=deadlineDate(c);if(!d)return c.expectedWindow?`TBA · 预计 ${c.expectedWindow}`:"TBA · 等待官方公布";return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23",timeZone:state.timezone==="beijing"?"Asia/Shanghai":undefined,timeZoneName:"short"}).format(d)}
function formatDateColumn(c,e){const d=deadlineDate(c),m=e.querySelector(".date-month"),day=e.querySelector(".date-day"),y=e.querySelector(".date-year");if(!d){e.classList.add("is-tba");m.textContent=c.expectedWindow||"DATE";day.textContent="TBA";y.textContent=c.edition;return}const tz=state.timezone==="beijing"?"Asia/Shanghai":undefined;m.textContent=new Intl.DateTimeFormat("en",{month:"short",timeZone:tz}).format(d);day.textContent=new Intl.DateTimeFormat("en",{day:"2-digit",timeZone:tz}).format(d);y.textContent=new Intl.DateTimeFormat("en",{year:"numeric",timeZone:tz}).format(d)}
function countdownText(c){const d=deadlineDate(c);if(!d)return"待官方公布";const distance=d.getTime()-Date.now();if(distance<=0)return"截稿已结束";const days=Math.floor(distance/86400000),hours=Math.floor(distance%86400000/3600000);if(days>0)return`还剩 ${days} 天 ${hours} 小时`;return`还剩 ${hours} 小时 ${Math.floor(distance%3600000/60000)} 分钟`}
function cardFor(c){const f=elements.template.content.cloneNode(true),card=f.querySelector(".conference-card"),date=f.querySelector(".date-column"),badges=f.querySelector(".badges"),count=f.querySelector(".countdown"),source=f.querySelector(".source-link");formatDateColumn(c,date);f.querySelector(".conference-meta").textContent=`${c.area} · ${c.edition}`;f.querySelector(".conference-title").textContent=`${c.acronym} ${c.edition}`;f.querySelector(".conference-description").textContent=c.name;f.querySelector(".deadline-label").textContent=`${c.deadlineType}：`;f.querySelector(".deadline-value").textContent=formatDeadline(c);const area=document.createElement("span");area.className="badge";area.textContent=areaLabels[c.area]||c.area;badges.append(area);if(c.ccf){const b=document.createElement("span");b.className=`badge ccf-${c.ccf.toLowerCase()}`;b.textContent=`CCF ${c.ccf}`;badges.append(b)}count.textContent=countdownText(c);if(!c.deadline)count.classList.add("is-tba");else if(deadlineDate(c)<=new Date()){count.classList.add("is-past");card.dataset.past="true"}source.href=c.source;source.setAttribute("aria-label",`查看 ${c.acronym} 官方来源`);return f}
function filteredConferences(){const q=state.query.trim().toLowerCase();return state.conferences.filter(c=>state.area==="All"||c.area===state.area).filter(c=>state.ccf==="all"||state.ccf==="none"&&!c.ccf||c.ccf===state.ccf).filter(c=>!q||[c.acronym,c.name,c.area,c.edition].some(v=>String(v).toLowerCase().includes(q))).sort((a,b)=>a.deadline&&b.deadline?deadlineDate(a)-deadlineDate(b):a.deadline?-1:b.deadline?1:a.sortDate.localeCompare(b.sortDate))}
function render(){const c=filteredConferences();elements.list.replaceChildren(...c.map(cardFor));elements.empty.hidden=c.length!==0;elements.list.hidden=c.length===0}
function renderAreaFilters(){Object.entries(areaLabels).forEach(([value,label])=>{const b=document.createElement("button");b.type="button";b.className=`filter-button${value===state.area?" active":""}`;b.textContent=label;b.dataset.area=value;b.addEventListener("click",()=>{state.area=value;elements.areaFilters.querySelectorAll(".filter-button").forEach(i=>i.classList.toggle("active",i===b));render()});elements.areaFilters.append(b)})}
function updateSummary(){const now=new Date();elements.upcomingCount.textContent=state.conferences.filter(c=>c.deadline&&deadlineDate(c)>now).length;elements.tbaCount.textContent=state.conferences.filter(c=>!c.deadline).length;elements.conferenceCount.textContent=state.conferences.length}
async function loadConferences(){try{const r=await fetch("./data/conferences.json");if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();state.conferences=p.conferences;elements.lastUpdated.textContent=`数据更新时间：${p.lastUpdated}`;updateSummary();render()}catch(e){console.error(e);elements.list.innerHTML='<div class="loading-state">数据加载失败，请稍后刷新页面。</div>'}}
elements.search.addEventListener("input",e=>{state.query=e.target.value;render()});elements.ccfFilter.addEventListener("change",e=>{state.ccf=e.target.value;render()});elements.timezoneToggle.addEventListener("click",()=>{state.timezone=state.timezone==="local"?"beijing":"local";elements.timezoneToggle.textContent=state.timezone==="local"?"显示北京时间":"显示本地时间";render()});renderAreaFilters();loadConferences();setInterval(render,60000);
